// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type File struct {
	ID              int32          `json:"id"`
	FileUri         string         `json:"file_uri"`
	FileThumnailUri sql.NullString `json:"file_thumnail_uri"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type PaymentDetail struct {
	ID         int32         `json:"id"`
	PurchaseID int32         `json:"purchase_id"`
	UserID     sql.NullInt32 `json:"user_id"`
	FileID     sql.NullInt32 `json:"file_id"`
}

type Product struct {
	ProductID int32          `json:"product_id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Name      sql.NullString `json:"name"`
	Category  sql.NullInt32  `json:"category"`
	Qty       sql.NullInt32  `json:"qty"`
	Price     sql.NullString `json:"price"`
	Sku       sql.NullString `json:"sku"`
	FileID    sql.NullInt32  `json:"file_id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type ProductCategory struct {
	ProductCategoryID int32          `json:"product_category_id"`
	Name              sql.NullString `json:"name"`
}

type Purchase struct {
	ID                  int32          `json:"id"`
	SenderName          sql.NullString `json:"sender_name"`
	SenderContactType   sql.NullString `json:"sender_contact_type"`
	SenderContactDetail sql.NullString `json:"sender_contact_detail"`
	Total               sql.NullInt32  `json:"total"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type PurchaseItem struct {
	ID         int32          `json:"id"`
	PurchaseID int32          `json:"purchase_id"`
	ProductID  int32          `json:"product_id"`
	Total      sql.NullString `json:"total"`
	Qty        sql.NullInt32  `json:"qty"`
}

type User struct {
	ID                int32          `json:"id"`
	FileID            sql.NullInt32  `json:"file_id"`
	Email             string         `json:"email"`
	Phone             string         `json:"phone"`
	BankAccountName   sql.NullString `json:"bank_account_name"`
	BankAccountHolder sql.NullString `json:"bank_account_holder"`
	BankAccountNumber sql.NullString `json:"bank_account_number"`
	Password          string         `json:"password"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}
