// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase.sql

package repository

import (
	"context"
	"database/sql"
)

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (sender_name, sender_contact_type, sender_contact_detail, total, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
    RETURNING id, created_at
`

type CreatePurchaseParams struct {
	SenderName          sql.NullString `json:"sender_name"`
	SenderContactType   sql.NullString `json:"sender_contact_type"`
	SenderContactDetail sql.NullString `json:"sender_contact_detail"`
	Total               sql.NullInt32  `json:"total"`
}

type CreatePurchaseRow struct {
	ID        int32        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (CreatePurchaseRow, error) {
	row := q.db.QueryRowContext(ctx, createPurchase,
		arg.SenderName,
		arg.SenderContactType,
		arg.SenderContactDetail,
		arg.Total,
	)
	var i CreatePurchaseRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createPurchaseItem = `-- name: CreatePurchaseItem :exec
INSERT INTO purchase_item (purchase_id, product_id, qty, total)
VALUES ($1, $2, $3, $4)
`

type CreatePurchaseItemParams struct {
	PurchaseID int32          `json:"purchase_id"`
	ProductID  int32          `json:"product_id"`
	Qty        sql.NullInt32  `json:"qty"`
	Total      sql.NullString `json:"total"`
}

func (q *Queries) CreatePurchaseItem(ctx context.Context, arg CreatePurchaseItemParams) error {
	_, err := q.db.ExecContext(ctx, createPurchaseItem,
		arg.PurchaseID,
		arg.ProductID,
		arg.Qty,
		arg.Total,
	)
	return err
}

const getProductCategoryByID = `-- name: GetProductCategoryByID :one
SELECT name FROM product_category WHERE product_category_id = $1
`

// New query to fetch a category name by its ID.
func (q *Queries) GetProductCategoryByID(ctx context.Context, productCategoryID int32) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getProductCategoryByID, productCategoryID)
	var name sql.NullString
	err := row.Scan(&name)
	return name, err
}

const getProductForUpdate = `-- name: GetProductForUpdate :one
SELECT
    product_id, user_id, name, category, qty, price, sku, file_id, created_at, updated_at
FROM products
WHERE product_id = $1
    FOR UPDATE
`

// This query now only fetches from the products table, without the JOIN.
func (q *Queries) GetProductForUpdate(ctx context.Context, productID int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductForUpdate, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.UserID,
		&i.Name,
		&i.Category,
		&i.Qty,
		&i.Price,
		&i.Sku,
		&i.FileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerBankDetailsByUserID = `-- name: GetSellerBankDetailsByUserID :one
SELECT bank_account_name, bank_account_holder, bank_account_number
FROM users
WHERE id = $1
`

type GetSellerBankDetailsByUserIDRow struct {
	BankAccountName   sql.NullString `json:"bank_account_name"`
	BankAccountHolder sql.NullString `json:"bank_account_holder"`
	BankAccountNumber sql.NullString `json:"bank_account_number"`
}

func (q *Queries) GetSellerBankDetailsByUserID(ctx context.Context, id int32) (GetSellerBankDetailsByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSellerBankDetailsByUserID, id)
	var i GetSellerBankDetailsByUserIDRow
	err := row.Scan(&i.BankAccountName, &i.BankAccountHolder, &i.BankAccountNumber)
	return i, err
}
